export const DARK_THEME_COLORS = {
    brandColor: "#39FF14",
    textColor: "#fff",
    backgroundColor: "#000",
    textColorInverse: "#000",
    primaryColor: "#1a1a1a",
    mutedIconColor: "#666",
    mutedTextColor: "#ddd",
    mutedTextColorInverse: "#333",
    voiceWaveformColor: "#EF4444",
    dangerColor: "#E7000B",
    dangerColorInverse: "#F9423C",
    borderColor: "#333",
    brandRGB: "0, 183, 0",
    taskCompletedColor: "#007AFF",
    warningColor: "#F59E0B",
    taskIncompleteColor: "#888",
    placeholderTextColor: "#888",
    disabledColor: "#39393D",
};

export const LIGHT_THEME_COLORS = {
    warningColor: "#F59E0B",
    taskCompletedColor: "#007AFF",
    placeholderTextColor: "#999",
    taskIncompleteColor: "#888",
    brandRGB: "57, 255, 20",
    brandColor: "#00B700",
    dangerColor: "#F9423C",
    dangerColorInverse: "#E7000B",
    borderColor: "#e5e5e5",
    textColor: "#000",
    backgroundColor: "#fff",
    textColorInverse: "#fff",
    primaryColor: "#f5f5f5",
    mutedIconColor: "#888",
    mutedTextColor: "#333",
    mutedTextColorInverse: "#ddd",
    voiceWaveformColor: "#EF4444",
    disabledColor: "#E9E9EA",
};
