import { StyleSheet } from "react-native"

// Styles remain the same
export const scanStyles = StyleSheet.create({
    container: { flex: 1 },
    header: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 16,
        paddingBottom: 12,
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        zIndex: 10,
    },
    closeButton: {
        width: 44,
        height: 44,
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 22,
    },
    headerTitle: {
        fontSize: 17,
        fontWeight: "600",
        letterSpacing: -0.3,
    },
    centeredContainer: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
        padding: 24,
    },
    permissionText: {
        fontSize: 17,
        textAlign: "center",
        marginBottom: 24,
        lineHeight: 26,
    },
    permissionButton: {
        backgroundColor: "#D97706",
        paddingVertical: 14,
        paddingHorizontal: 28,
        borderRadius: 12,
        minHeight: 56,
        justifyContent: "center",
    },
    permissionButtonText: {
        color: "#fff",
        fontSize: 17,
        fontWeight: "600",
    },
    cameraContainer: { flex: 1 },
    modelStatusBanner: {
        position: "absolute",
        top: 120,
        left: 20,
        right: 20,
        backgroundColor: "rgba(59, 130, 246, 0.95)",
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 8,
    },
    modelStatusText: {
        color: "#fff",
        textAlign: "center",
        fontSize: 14,
        fontWeight: "500",
    },
    captureButtonContainer: {
        position: "absolute",
        bottom: 0,
        left: 0,
        right: 0,
        alignItems: "center",
    },
    captureButton: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: "#fff",
        alignItems: "center",
        justifyContent: "center",
        shadowColor: "#fff",
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.35,
        shadowRadius: 16,
        elevation: 12,
    },
    captureButtonDisabled: { opacity: 0.5 },
    errorBanner: {
        position: "absolute",
        bottom: 160,
        left: 20,
        right: 20,
        backgroundColor: "rgba(239, 68, 68, 0.95)",
        paddingVertical: 14,
        paddingHorizontal: 20,
        borderRadius: 12,
    },
    errorText: {
        color: "#fff",
        textAlign: "center",
        fontSize: 15,
        fontWeight: "500",
    },
    processingText: {
        marginTop: 20,
        fontSize: 17,
        fontWeight: "500",
    },
    subText: {
        marginTop: 8,
        fontSize: 14,
    },
    cancelButton: {
        marginTop: 24,
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 8,
        borderWidth: 1,
    },
    cancelButtonText: {
        fontSize: 15,
        fontWeight: "500",
    },
    reviewContainer: {
        flex: 1,
        paddingTop: 80,
    },
    reviewContent: { padding: 16 },
    imagePreviewContainer: {
        borderRadius: 16,
        overflow: "hidden",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 4,
    },
    imagePreview: {
        width: "100%",
        height: 300,
        borderRadius: 16,
    },
    confidenceBadge: {
        position: "absolute",
        bottom: 12,
        right: 12,
    },
    confidenceText: {
        color: "#fff",
        fontSize: 12,
        fontWeight: "600",
    },
    textSection: { marginBottom: 24 },
    sectionTitle: {
        fontSize: 14,
        fontWeight: "600",
        marginBottom: 12,
        textTransform: "uppercase",
        letterSpacing: 0.5,
        opacity: 0.7,
    },
    textInput: {
        fontSize: 17,
        lineHeight: 28,
        padding: 16,
        borderWidth: 1,
        minHeight: 200,
    },
    actionButtons: {
        flexDirection: "row",
        gap: 12,
    },
    actionButton: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        height: 56,
        borderRadius: 12,
        gap: 8,
    },
    primaryButton: { backgroundColor: "#3B82F6" },
    secondaryButton: { borderWidth: 1 },
    actionButtonText: {
        fontSize: 17,
        fontWeight: "600",
    },
    mask: { ...StyleSheet.absoluteFillObject, top: -100 },
    maskTop: { flex: 1, backgroundColor: "rgba(0,0,0,0.55)" },
    maskMiddle: { flexDirection: "row" },
    maskSide: { flex: 1, backgroundColor: "rgba(0,0,0,0.55)" },
    scanFrame: {
        width: "85%",
        aspectRatio: 0.7,
        borderWidth: 2,
        borderColor: "#fff",
    },
    maskBottom: { flex: 1, backgroundColor: "rgba(0,0,0,0.55)" },
})
